name: suscribo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_local_notifications: ^19.5.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  go_router: ^14.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/lottie/
